name: roadscan
description: Road Crack Detection App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  image_picker: ^0.8.7+5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.0
  font_awesome_flutter: ^10.0.0
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/app_icon.png"  # Path to your app icon
  adaptive_icon_background: "#ffffff"  # Background color for adaptive icon (Android)
  adaptive_icon_foreground: "lib/images/app_icon.png"  # Foreground image (Android)

flutter:
  uses-material-design: true

  assets:
    - lib/images/app_icon.png  # Ensure this asset is registered
